### ISSUE TITLE
Skript gibt Fehler aus

### ISSUE THREAD

**Issue by denjae** [adlerzei/Drei90Voter#1]
Ich kann das Skript mit Python 3.9 auf MacOS 10.15.7 nicht starten. 
Als Output erhalte ich lediglich den hinterlegten Fehlertext "Error. Please check script."

Ich kann nur nachvollziehen, dass das Skript die notwendigen Netzverbindungen herstellt. Danach wird der Fehler ausgegeben.

**Comment by adlerzei** [comment]
Versuch mal in Zeile 96 den Vergleich anzupassen, dass der Umlaut raus fliegt. Könnte ein Encoding Problem sein. Könntest zum Beispiel testweise die folgende Zeile versuchen:
 
`if "Herzlichen Dank f" in res.text:`

Hab gerade leider keine Möglichkeit das auf die Schnelle zu überprüfen.

**Comment by denjae** [comment]
Mit Änderung der Zeile funktioniert es, danke! Ich kann die Anpassung gern pushen wenn gewünscht.

**Comment by adlerzei** [comment]
Wenn du es sauber lösen möchtest kannst du gern einen Pull Request stellen, die Zeile so zu kürzen sollte aber nur ein Workaround sein. Wenn nicht mach ich es bei Gelegenheit.
